spring.application.name=moyeo
server.forward-headers-strategy=framework

logging.level.org.springframework=info
logging.level.com.mo.moyeo=DEBUG

# Import .env file
spring.config.import=optional:file:.env[.properties]

# MySQL ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB Source
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# jwt
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=900000000
jwt.refresh-token-expiration-ms=3600000

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# firebase
firebase.service-account.path=/firebase/moyeo-firebase-key.json

# fcm
fcm.default-topic-name=noti

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

management.endpoints.web.exposure.include=prometheus, health, info
management.metrics.tags.application=my-spring-app

