spring.application.name=moyeo
server.forward-headers-strategy=framework

logging.level.org.springframework=info
logging.level.com.mo.moyeo=DEBUG

# Import .env file
spring.config.import=optional:file:.env[.properties]

# MySQL ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB Source
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}
