spring.application.name=moyeo
server.forward-headers-strategy=framework

logging.level.org.springframework=info
logging.level.com.mo.moyeo=DEBUG

# Import .env file
spring.config.import=optional:file:.env[.properties]

# MySQL ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB Source
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# sms api
coolsms.api.key=${SMS_API_KEY}
coolsms.api.secret=${SMS_API_SECRET}
coolsms.sender-number=${SMS_SENDER_NUMBER}
coolsms.api.url=${SMS_API_URL}

# jwt
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=3600000


# moyeo api
moyeo.api.key=${MOYEO_API_KEY}
moyeo.api.base_url=${BASE_URL}
moyeo.api.auth_text=${MOYEO_API_AUTH_TEXT}
moyeo.api.endpoint.user_search=${USER_SEARCH_ENDPOINT}
moyeo.api.endpoint.open_auth=${OPEN_AUTH_ENDPOINT}
moyeo.api.endpoint.check_auth=${CHECK_AUTH_ENDPOINT}
moyeo.api.endpoint.demand_deposit=${DEMAND_DEPOSIT_ENDPOINT}
moyeo.api.account=${MOYEO_API_ACCOUNT}
moyeo.api.user_key=${MOYEO_API_USER_KEY}

# encryption
moyeo.encryption.key=${MOYEO_ENCRYPTION_KEY}

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# exchange
exchange.rate.get=${EXCHANGE_RATE_GET}

# common
moyeo.server.base_url=${SERVER_BASE_URL}

# firebase
firebase.service-account.path=/firebase/moyeo-firebase-key.json
firebase.project-id=${FIREBASE_PROJECT-ID}

# fcm
fcm.default-topic-name=noti

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

