version: '3.8'

services:
  app:
    build: .
    container_name: moyeo-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: moyeo-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: moyeo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql               # 데이터 영구 저장

volumes:
  mysql_data: