version: '3.8'

services:
  app:
    build: .
    container_name: moyeo-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: moyeo-redis
    ports:
      - "6379:6379"