services:
  app1:
    build: .
    container_name: moyeo-app1
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    networks:
      - monitoring

  app2:
    build: .
    container_name: moyeo-app2
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: moyeo-nginx
    ports:
      - "8080:80"   # 외부에서 접근할 포트
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - monitoring


  redis:
    image: redis:latest
    container_name: moyeo-redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

  mysql:
    image: mysql:latest
    container_name: moyeo-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring

volumes:
  mysql_data:

networks:
  monitoring:
    external: true
